### Send POST request with json body
POST http://localhost:4000/network
Content-Type: application/json

{
  "id": 31337,
  "name": "localhost",
  "url": "http://127.0.0.1:8545/"
}

### Send POST request with json body
POST http://localhost:4000/wallet/create
Content-Type: application/json

{
  "groupNumber": 1,
  "childWalletAmount": 1
}

### Send POST request with json body
POST http://localhost:4000/wallet/import
Content-Type: application/json

{
  "mnemonic": "glare patient beach layer design visit advice afford forest hurdle similar account",
  "childWalletAmount": 2
}

### Send POST request with json body
POST http://localhost:4000/balance
Content-Type: application/json

{
  "networkId": 31337,
  "walletAddress": "0x06043c6fc15FE8a68380e5899C5211970b560734"
}

### UPDATE
PATCH http://localhost:4000/balance/2
Content-Type: application/json

### MINT
POST http://localhost:4000/nft
Content-Type: application/json

{
  "networkId": 31337,
  "privateKey": "0x41ab6dcc0da73a9910d2477ceff955c9bf447cc1b39cc673055ad1d6a4f05988",
  "dropId": "0x1252e0850046f1736134ea7ee172f48a21c824e8",
  "merkleQuantity": 50,
  "quantity": 10,
  "proof": [
    "0x569b19c77eb0165916899ec573ad81519b591a1f5169d7f32d0c55815dde8d57"
  ]
}


### GET ONE
GET http://localhost:4000/network/31337

### GET ONE
GET http://localhost:4000/wallet/0x95926a5B8cbA6Df6db572fce9752e02D4E6D9fC3

### VOTE
POST http://localhost:4000/vote
Content-Type: application/json

{
  "jobId": 1,
  "proposal": 2,
  "votee": 1,
  "tokens": [6]
}

### VOTE
POST http://localhost:4000/nft/update
Content-Type: application/json

{
  "tokenId": 5,
  "isVoted": true
}

### VOTE
POST http://localhost:4000/queues/vote
Content-Type: application/json

{
  "networkId": 31337,
  "current": 0,
  "privateKeys": [
    "0xa3679728091163ae15498f9b7e2ad25414a789353e18c0535ef7327c1659f136",
    "0x41ab6dcc0da73a9910d2477ceff955c9bf447cc1b39cc673055ad1d6a4f05988"
  ],
  "target": 11,
  "proposalId": 1,
  "votee": 1
}
