### Send POST request with json body
POST http://localhost:3000/network
Content-Type: application/json

{
  "id": 420,
  "name": "optimism-goerli",
  "url": "https://optimism-goerli.publicnode.com"
}

### GET ALL
GET http://localhost:3000/network

### GET ONE
GET http://localhost:3000/network/420

### UPDATE
PATCH http://localhost:3000/network/1
Content-Type: application/json

{
  "name": "mainnet"
}

### DELETE
DELETE http://localhost:3000/network/420
